export const SCOPE_LABELS = {
    'playlist-read-private': 'Access your private playlists',
    'playlist-read-collaborative': 'Access your collaborative playlists',
    'playlist-modify-public': 'Manage your public playlists',
    'playlist-modify-private': 'Manage your private playlists',
    'streaming': 'Play music and control playback on your other devices',
    'user-follow-modify': 'Manage who you are following',
    'user-follow-read': 'Access your followers and who you are following',
    'user-library-read': 'Access your saved tracks and albums',
    'user-library-modify': 'Manage your saved tracks and albums',
    'user-read-private': 'Access your subscription details',
    'user-read-birthdate': 'Receive your birthdate',
    'user-read-email': 'Get your real email address',
    'user-top-read': 'Read your top artists and tracks',
    'user-modify-playback-state': 'Read your current playing activity',
    'user-read-currently-playing': 'Read your current playing tracks',
    'user-read-playback-state': 'Manage your current playing activity',
};
